
class Settings {
  bool sendInfo;
  int infoSent;
  int daemonPort;
  bool allowRemote;
  bool preAllocateStorage;
  String downloadLocation;
  List<dynamic> listenPorts;
  String listenInterface;
  String outgoingInterface;
  String randomPort;
  int listenRandomPort;
  bool listenUseSysPort;
  bool listenReusePort;
  List<dynamic> outgoingPorts;
  String randomOutgoingPorts;
  bool copyTorrentFile;
  bool delCopyTorrentFile;
  String torrentfilesLocation;
  String pluginsLocation;
  bool prioritizeFirstLastPieces;
  bool sequentialDownload;
  bool dht;
  bool upnp;
  bool natpmp;
  bool utpex;
  bool lsd;
  int encInPolicy;
  int encOutPolicy;
  int encLevel;
  int maxConnectionsGlobal;
  int maxUploadSpeed;
  int maxDownloadSpeed;
  int maxUploadSlotsGlobal;
  int maxHalfOpenConnections;
  int maxConnectionsPerSecond;
  bool ignoreLimitsOnLocalNetwork;
  int maxConnectionsPerTorrent;
  int maxUploadSlotsPerTorrent;
  int maxUploadSpeedPerTorrent;
  int maxDownloadSpeedPerTorrent;
  List<dynamic> enabledPlugins;
  bool addPaused;
  int maxActiveSeeding;
  int maxActiveDownloading;
  int maxActiveLimit;
  bool dontCountSlowTorrents;
  bool queueNewToTop;
  bool stopSeedAtRatio;
  bool removeSeedAtRatio;
  int stopSeedRatio;
  int shareRatioLimit;
  int seedTimeRatioLimit;
  int seedTimeLimit;
  bool autoManaged;
  bool moveCompleted;
  String moveCompletedPath;
  List<dynamic> moveCompletedPathsList;
  List<dynamic> downloadLocationPathsList;
  bool pathChooserShowChooserButtonOnLocalhost;
  bool pathChooserAutoCompleteEnabled;
  String pathChooserAcceleratorString;
  int pathChooserMaxPopupRows;
  bool pathChooserShowHiddenFiles;
  bool newReleaseCheck;
  Map<String, dynamic> proxy;
  String peerTos;
  bool rateLimitIpOverhead;
  String geoipDbLocation;
  int cacheSize;
  int cacheExpiry;
  bool autoManagePreferSeeds;
  bool shared;
  bool superSeeding;
  String autoaddLocation;

  Settings(Map<String, dynamic> json) {
    this.sendInfo = json['send_info'];
    this.infoSent = json["info_sent"];
    this.daemonPort = json["daemon_port"];
    this.allowRemote = json["allow_remote"];
    this.preAllocateStorage = json["pre_allocate_storage"];
    this.downloadLocation = json["download_location"];
    this.listenPorts = json["listen_ports"];
    this.listenInterface = json["listen_interface"];
    this.outgoingInterface = json["outgoing_interface"];
    this.randomPort = json["random_port"];
    this.listenRandomPort = json["listen_random_port"];
    this.listenUseSysPort = json["listen_use_sys_port"];
    this.listenReusePort = json["listen_reuse_port"];
    this.outgoingPorts = json["outgoing_ports"];
    this.randomOutgoingPorts = json["random_outgoing_ports"];
    this.copyTorrentFile = json["copy_torrent_file"];
    this.delCopyTorrentFile = json["del_copy_torrent_file"];
    this.torrentfilesLocation = json["torrentfiles_location"];
    this.pluginsLocation = json["plugins_location"];
    this.prioritizeFirstLastPieces = json["prioritize_first_last_pieces"];
    this.sequentialDownload = json["sequential_download"];
    this.dht = json["dht"];
    this.upnp = json["upnp"];
    this.natpmp = json["natpmp"];
    this.utpex = json["utpex"];
    this.lsd = json["lsd"];
    this.encInPolicy = json["enc_in_policy"];
    this.encOutPolicy = json["enc_out_policy"];
    this.encLevel = json["enc_level"];
    this.maxConnectionsGlobal = json["max_connections_global"];
    this.maxUploadSpeed = json["max_upload_speed"];
    this.maxDownloadSpeed = json["max_download_speed"];
    this.maxUploadSlotsGlobal = json["max_upload_slots_global"];
    this.maxHalfOpenConnections = json["max_half_open_connections"];
    this.maxConnectionsPerSecond = json["max_connections_per_second"];
    this.ignoreLimitsOnLocalNetwork = json["ignore_limits_on_local_network"];
    this.maxConnectionsPerTorrent = json["max_connections_per_torrent"];
    this.maxUploadSlotsPerTorrent = json["max_upload_slots_per_torrent"];
    this.maxUploadSpeedPerTorrent = json["max_upload_speed_per_torrent"];
    this.maxDownloadSpeedPerTorrent = json["max_download_speed_per_torrent"];
    this.enabledPlugins = json["enabled_plugins"];
    this.addPaused = json["add_paused"];
    this.maxActiveSeeding = json["max_active_seeding"];
    this.maxActiveDownloading = json["max_active_downloading"];
    this.maxActiveLimit = json["max_active_limi"];
    this.dontCountSlowTorrents = json["dont_count_slow_torrents"];
    this.queueNewToTop = json["queue_new_to_top"];
    this.stopSeedAtRatio = json["stop_seed_at_ratio"];
    this.removeSeedAtRatio = json["remove_seed_at_ratio"];
    this.stopSeedRatio = json["stop_seed_ratio"];
    this.shareRatioLimit = json["share_ratio_limit"];
    this.seedTimeRatioLimit = json["seed_time_ratio_limit"];
    this.seedTimeLimit = json["seed_time_limit"];
    this.autoManaged = json["auto_managed"];
    this.moveCompleted = json["move_completed"];
    this.moveCompletedPath = json["move_completed_path"];
    this.moveCompletedPathsList = json["move_completed_paths_list"];
    this.downloadLocationPathsList = json["download_location_paths_list"];
    this.pathChooserShowChooserButtonOnLocalhost =
        json["path_chooser_show_chooser_button_on_localhost"];
    this.pathChooserAutoCompleteEnabled =
        json["path_chooser_auto_complete_enabled"];
    this.pathChooserAcceleratorString = json["path_chooser_accelerator_string"];
    this.pathChooserMaxPopupRows = json["path_chooser_max_popup_rows"];
    this.pathChooserShowHiddenFiles = json["path_chooser_show_hidden_files"];
    this.newReleaseCheck = json["new_release_check"];
    this.proxy = json["proxy"];
    this.peerTos = json["peer_tos"];
    this.rateLimitIpOverhead = json["rate_limit_ip_overhead"];
    this.geoipDbLocation = json["geoip_db_location"];
    this.cacheSize = json["cache_size"];

    this.cacheExpiry = json["cache_expiry"];
    this.autoManagePreferSeeds = json["auto_manage_prefer_seeds"];
    this.shared = json["shared"];
    this.superSeeding = json["super_seeding"];
    this.autoaddLocation = json["autoadd_location"];
  }
}
